### ISSUE TITLE
liqoctl installed from homebrew dumps a 1000+ line stack trace

### ISSUE THREAD

**Issue by oskapt** [liqotech/liqo#971]
#### What happened:

Every non-help option provided to `liqoctl` dumps a stack trace > 1000 lines long. It's not clear if it also does what's requested. It almost looks like `strace` output, like there's some debug flag that got left on when it was compiled.

```
...
goroutine 62 [IO wait]:
internal/poll.runtime_pollWait(0xc615660, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000456300, 0xc000e55800, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000456300, {0xc000e55800, 0x704, 0x704})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000456300, {0xc000e55800, 0xc000204ea0, 0xc000204fc0})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00043a1e8, {0xc000e55800, 0xc0002058c0, 0xc00066c7f8})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0006a0468, {0xc000e55800, 0x0, 0x100964d})
        crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00094de78, {0x2e67080, 0xc0006a0468})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00094dc00, {0xc5f2888, 0xc00043a1e8}, 0xc0002aba40)
        crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00094dc00, 0x0)
        crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00094dc00, {0xc0005f0000, 0x1000, 0x101000000000000})
        crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc000562000, {0xc0005f0000, 0x1004c9d, 0x60})
        net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc0006a5e00)
        bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc0006a5e00, 0x1)
        bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc000562000)
        net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        net/http/transport.go:1747 +0x1e05
...
```

#### How to reproduce it (as minimally and precisely as possible):

```
brew install liqoctl
liqoctl generate-add-command
```

#### Anything else we need to know?:

I uninstalled it and then installed the binary from the releases page, and the problem no longer occurs.

#### Environment:
- Liqo version: Whatever is current in homebrew
- Kubernetes version (use `kubectl version`): k3s 1.19.5
- macOS Big Sur 11.6

**Comment by oskapt** [comment]
Yes, it seems to work better now, unless it's being asked to do something incorrect. For example, if I run `liqo generate-add-command` without first running `liqoctl install`, it dumps the same >1000 line stack trace. This overflows any actual error response that might show what the problem is. 

Even when running `liqoctl install` it spits out some debug information that I don't think should be there (marked with a comment below). It's just _way_ too verbose.

```
➤ liqoctl install k3s
* Initializing installer... 🔌
* Retrieving cluster configuration from cluster provider... 📜
* Installing or Upgrading Liqo... (this may take few minutes) ⏳
E1104 16:16:19.306900   63587 memcache.go:196] continuing     ## <--- THIS LINE
2021/11/04 16:16:59 release installed successfully: liqo/liqo-v0.3.1
* All Set! You can use Liqo now! 🚀
I1104 16:16:59.887411   63587 cluster_info.go:72] ClusterID is '8047a665-c333-4e4c-91bb-e5b996e34bf1'
```

**Comment by palexster** [comment]
Hi @oskapt, thanks for reporting this.  We are working on having a clean output in liqoctl and, in particular, avoiding ineffective messages in the next release.
